### ISSUE TITLE
k8s-ingress

### ISSUE THREAD

**Issue by kimgamjaaaaa** [kimgamjaaaaa/ingress#1]
```
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
        name: marver-ingress
        annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/rewrite-target: /
spec:
        rules:
                - http:
                        paths:
                                - path: /
                                  pathType: Prefix
                                  backend:
                                          service:
                                                  name: webserver
                                                  port:
                                                          number: 8080
                                - path: /marvel
                                  pathType: Prefix
                                  backend:
                                          service:
                                                  name: marvel-service
                                                  port:
                                                          number: 80
```

All pods and services are up and running and the ingress is reachable, but in the case of multi-path one is not showing up normally. give me help

**Comment by kimgamjaaaaa** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
        name: web
        labels:
                app: web
spec:
        replicas: 3
        selector:
                matchLabels:
                        app: web
        template:
                metadata:
                        labels:
                                app: web
                spec:
                        containers:
                                - name: web
                                  image: gamjadocker/web:2.0
                                  volumeMounts:
                                          - mountPath: /var/www/html
                                            name: htmldata
                                  ports:
                                          - containerPort: 80
                        volumes:
                                - name: htmldata
                                  hostPath:
                                          path: /home/test01/htmldata
                                          type: Directory
#hostPath type check failed: /home/test01/htmldata is not a Directory 

# type: Directory >> type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
        name: webserver
spec:
        ports:
                - port: 8080      # 서비스 포트
                  targetPort: 80   # 컨테이너 포트(pod 포트)
                  protocol: TCP
                  name: http
        selector:
                app: web
```

**Comment by kimgamjaaaaa** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
        name: marvel-home
spec:
        replicas: 1
        selector:
                matchLabels:
                        name: marvel
        template:
                metadata:
                        labels:
                                name: marvel
                spec:
                        containers:
                                - image: smlinux/marvel-collection
                                  name: marvel-container
                                  ports:
                                          - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
        name: marvel-service
spec:
        ports:
                - port: 80       # 서비스 포트
                  targetPort: 80  # 컨테이너 포트(pod 포트)
                  protocol: TCP
        selector:
                  name: marvel
```
